<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<RootNamespace>FlightLib</RootNamespace>
	<AssemblyName>FlightLib</AssemblyName>
	<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
	<Compile Include="FlightPlan.cs" />
	<Compile Include="FlightPlanLib.cs" />
	<Compile Include="Position.cs" />
	<Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>

</Project>